In [33]:
import numpy as np

In [39]:
# creating 9 x 9 grid
grid = np.full((9,9), -1)

start = (0,0)
end = (4,4)

grid[start[0], start[1]] = 0
grid[end[0], end[1]] = 99

cp = start


not_explored = [(0,0,0)]

print(grid)

[[ 0 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 99 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1]]


In [40]:
#function to check next possible moves
def next_possible_moves(point):
    row = point[0]
    column = point[1]
    depth = point[2]
    
    moves = [(row - 1, column), (row + 1, column), (row, column - 1), (row, column + 1)]
    
    for m in moves: 
        if m == end:
            return 1
        else:
            if m[0] >= 0 and m[0] <= 8 and m[1] >= 0 and m[1] <= 8 and grid[m[0], m[1]] == -1 and grid[m[0], m[1]] != -2: 
                not_explored.append(((m[0]), m[1], depth + 1))
                grid[m[0], m[1]] = depth + 1
    
    return 0
    
            

In [41]:
def sort_not_explored():
    arr = not_explored
    n = len(arr)
 
    # Traverse through all array elements
    for i in range(n-1):
    # range(n) also work but outer loop will
    # repeat one time more than needed.
 
        # Last i elements are already in place
        for j in range(0, n-i-1):
 
            # traverse the array from 0 to n-i-1
            # Swap if the element found is greater
            # than the next element
            if arr[j][2] > arr[j + 1][2] :
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
              

In [42]:
while True:
    r = next_possible_moves(not_explored[0])
    if r == 1: 
        break
    
    not_explored.pop(0)
    sort_not_explored

In [43]:
print(grid)

[[ 0  1  2  3  4  5  6  7 -1]
 [ 1  2  3  4  5  6  7 -1 -1]
 [ 2  3  4  5  6  7 -1 -1 -1]
 [ 3  4  5  6  7 -1 -1 -1 -1]
 [ 4  5  6  7 99 -1 -1 -1 -1]
 [ 5  6  7  8 -1 -1 -1 -1 -1]
 [ 6  7  8 -1 -1 -1 -1 -1 -1]
 [ 7  8 -1 -1 -1 -1 -1 -1 -1]
 [ 8 -1 -1 -1 -1 -1 -1 -1 -1]]


In [44]:
not_explored

[(4, 3, 7),
 (3, 4, 7),
 (2, 5, 7),
 (1, 6, 7),
 (0, 7, 7),
 (8, 0, 8),
 (7, 1, 8),
 (6, 2, 8),
 (5, 3, 8)]